# name: Deploy to Google Cloud VM

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v3
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#           pip install pytest

#       - name: Run tests
#         run: |
#           pytest

#       # Setup GCloud CLI
#       - id: 'auth'
#         name: 'Authenticate to Google Cloud'
#         uses: 'google-github-actions/auth@v1'
#         with:
#           credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v1'

#       # Deploy using SSH
#       - name: Deploy to VM
#         run: |
#           echo "${{ secrets.GCP_SSH_KEY }}" > ssh_key
#           chmod 600 ssh_key
#           gcloud compute scp --zone "${{ secrets.GCP_ZONE }}" --project "${{ secrets.GCP_PROJECT_ID }}" \
#             --ssh-key-file=ssh_key \
#             -r ./* ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_NAME }}:~/app/
#           gcloud compute ssh --zone "${{ secrets.GCP_ZONE }}" --project "${{ secrets.GCP_PROJECT_ID }}" \
#             --ssh-key-file=ssh_key \
#             ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_NAME }} \
#             --command='cd ~/app && docker-compose up -d --build' 